<a href="https://colab.research.google.com/github/juancuevas-ops/inteligencia-artificial/blob/main/Tensor_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import torch
import numpy as np

# Inicializar un tensor
Los tensores se pueden inicializar de varias formas. Echa un vistazo a los siguientes ejemplos:

Directamente desde los datos
Los tensores se pueden crear directamente a partir de datos. El tipo de datos se infiere automáticamente.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

tranformacion automatica de datos a un tensor

In [20]:
data

[[1, 2], [3, 4]]

In [19]:
x_data

tensor([[1, 2],
        [3, 4]])

Desde una matriz NumPy
Los tensores se pueden crear a partir de matrices NumPy y viceversa. Dado que numpy 'np_array' y tensor 'x_np' comparten la misma ubicación de memoria aquí, cambiar el valor de uno cambiará el otro

In [23]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"valor del array de numpy: \n {np_array} \n")
print(f"Valor del array de numpy: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array después de la operación * 2: \n {np_array} \n")
print(f"Tensor x_np valor después de modificar la matriz numpy: \n {x_np} \n")

valor del array de numpy: 
 [[1 2]
 [3 4]] 

Valor del array de numpy: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array después de la operación * 2: 
 [[2 4]
 [6 8]] 

Tensor x_np valor después de modificar la matriz numpy: 
 tensor([[2, 4],
        [6, 8]]) 



De otro tensor:
El nuevo tensor conserva las propiedades (forma, tipo de datos) del tensor del argumento, a menos que se anule explícitamente.

In [25]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Tensor de unidades: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Tensor aleatorio: \n {x_rand} \n")

Tensor de unidades: 
 tensor([[1, 1],
        [1, 1]]) 

Tensor aleatorio: 
 tensor([[0.0883, 0.1705],
        [0.0132, 0.8954]]) 



Con valores aleatorios o constantes:
forma es una tupla de dimensiones tensoriales. En las funciones siguientes, determina la dimensionalidad del tensor de salida. La forma muestra el número de filas y columnas en el tensor. P.ej. forma = (# de filas, # de columnas).

In [26]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Tensor Aleatorio: \n {rand_tensor} \n")
print(f"Tensor de unidades: \n {ones_tensor} \n")
print(f"Tensor con ceros: \n {zeros_tensor}")

Tensor Aleatorio: 
 tensor([[0.8124, 0.8601, 0.7806],
        [0.2010, 0.9662, 0.0766]]) 

Tensor de unidades: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Tensor con ceros: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



Con valores aleatorios o constantes:
forma es una tupla de dimensiones tensoriales. En las funciones siguientes, determina la dimensionalidad del tensor de salida. La forma muestra el número de filas y columnas en el tensor. P.ej. forma = (# de filas, # de columnas).


In [27]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Con valores aleatorios o constantes:
forma es una tupla de dimensiones tensoriales. En las funciones siguientes, determina la dimensionalidad del tensor de salida. La forma muestra el número de filas y columnas en el tensor. P.ej. forma = (# de filas, # de columnas).

In [28]:
# Movemos nuestro tensor a la GPU si está disponible
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [29]:
tensor

tensor([[0.2341, 0.8334, 0.4738, 0.3557],
        [0.4970, 0.9189, 0.4060, 0.3508],
        [0.3250, 0.5465, 0.4629, 0.2608]])

Pruebe algunas de las operaciones de la lista. Si está familiarizado con la API de NumPy, encontrará que la API de Tensor es muy fácil de usar.

Indexación y corte estándar de tipo numpy:

In [30]:
tensor = torch.ones(4, 4)
print('Primera Fila: ',tensor[0])
print('Primera Columna: ', tensor[:, 0])
print('última columna:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Primera Fila:  tensor([1., 1., 1., 1.])
Primera Columna:  tensor([1., 1., 1., 1.])
última columna: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Unión de tensores
Puedes usar torch.cat para concatenar una secuencia de tensores a lo largo de una dimensión determinada. torch.stack es otra opción de unión de tensores que es sutilmente diferente de torch.cat.

In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


# Operaciones aritmeticas

In [39]:
# Esto calcula la multiplicación de matrices entre dos tensores. y1, y2, y3 tendrán el mismo valor
y1_1 = tensor @ tensor.T
y2_2 = tensor.matmul(tensor.T)

y3_3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3_3)


# Esto calcula el producto por elementos. z1, z2, z3 tendrán el mismo valor
z1_z = tensor * tensor
z2_z = tensor.mul(tensor)

z3_z = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3_z)

tensor([[36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.]])

Tensores de un solo elemento
Si tiene un tensor de un elemento, por ejemplo agregando todos los valores de un tensor en un solo valor, puede convertirlo en un valor numérico de Python usando item():

In [13]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [35]:
type(agg)

torch.Tensor

operaciones de n lugares
Las operaciones que almacenan el resultado en el operando se denominan in situ. Se denotan con un sufijo _. Por ejemplo: x.copy_(y), x.t_(), cambiará x.

Nota: las operaciones en el lugar ahorran algo de memoria, pero pueden ser problemáticas al calcular derivados debido a una pérdida inmediata de la historia. Por lo tanto, se desaconseja su uso.

In [36]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Puente con NumPy
Los tensores en la CPU y las matrices NumPy pueden compartir sus ubicaciones de memoria subyacentes, y cambiar uno cambiará el otro.

Tensor a matriz NumPy


In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Un cambio en el tensor se refleja en la matriz NumPy.

In [16]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Matriz NumPy a Tensor

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

Los cambios en la matriz NumPy se reflejan en el tensor.

In [18]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
